version: '3'

services:
  database:
    image: mariadb
    volumes:
    - ${DB_PATH}:/var/lib/mysql
    ports:
    - 2000:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
      TZ: ${TZ}